version: "3.8"

services:
  db:
    image: postgres
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"

  api:
    build: .
    container_name: fastapi_backend
    ports:
      - "8000:8000"
    depends_on:
      - db
